pipeline {
    agent any

    environment {
        GRADLEW_DIR = 'Modulo4_CICD/jenkins-resources/calculator'
        GRADLE_CMD = './gradlew'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh "${env.GRADLE_CMD} compileJava"
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh "${env.GRADLE_CMD} test"
                }
            }
        }
    }
}