pipeline {
    agent any

    environment {
        GRADLEW_DIR = 'Modulo4_CICD/jenkins-resources/calculator'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh './gradlew build' 
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh './gradlew test'
                }
            }
        }
    }
}