apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80            # Puerto externo
    targetPort: 3000    # Puerto interno del contenedor