pipeline {
    agent any

    environment {
        GRADLEW_DIR = 'Modulo 4 - CICD/jenkins-resources'
        GRADLE_CMD = './gradlew'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/molmo073/lemoncode_bootcamp_devops.git', branch: 'main'
            }
        }

        stage('Compile') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh "${env.GRADLE_CMD} compileJava"
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh "${env.GRADLE_CMD} test"
                }
            }
        }
    }
}
