services:
  api:
    build:
      context: ./hangman-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  front:
    build:
      context: ./hangman-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3001