apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dynamic
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

  