apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: lemoncodersbc/lc-todo-monolith:v5-2024
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-app-config
