apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo-app-deployment
spec:                 # Especificación del Deployment
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:           # Plantilla del Pod
    metadata:
      labels:
        app: todo-app
    spec:             # Especificación del Pod
      containers:
      - name: todo-app
        image: lemoncodersbc/lc-todo-monolith:v5-2024
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"