services:
  mongodb:
    image: mongo
    container_name: some-mongo
    networks:
      - lemoncode-challenge
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./node-stack/backend
      dockerfile: Dockerfile
    container_name: backend-api
    networks:
      - lemoncode-challenge
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://some-mongo:27017
    env_file:
    - ./node-stack/backend/.env.template

  frontend:
    build:
      context: ./node-stack/frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    networks:
      - lemoncode-challenge
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      - API_URI=http://backend-api:5000/api/topics

networks:
  lemoncode-challenge:
    name: lemoncode-challenge

volumes:
  mongo-data:
