pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
            args '-u root'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                sh './gradlew build'
            }
        }

        stage('Unit Tests') {
            steps {
                sh './gradlew test'
            }
        }
    }
}
