pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
            args '-u root'
        }
    }

    environment {
        GRADLEW_DIR = 'Modulo4_CICD/Jenkins/jenkins-resources/calculator'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("${env.GRADLEW_DIR}") {
                    sh './gradlew test'
                }
            }
        }
    }
}

