name: CD Frontend

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v4

    - name: Login en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build de imagen Docker
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/hangman-frontend:latest Modulo4_CICD/Github\ Actions/.start-code/hangman-front

    - name: Push de la imagen a GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/hangman-frontend:latest
